### ISSUE TITLE
irb for ruby 2.0.0

### ISSUE THREAD

**Issue by michaelachrisco** [shaper/yahoo-weather#6]
When intiating the ruby gem as `require yahoo-weather`
the following error occured: 

```
require 'yahoo-weather'
SyntaxError: /home/mesa/.rvm/gems/ruby-2.0.0-p247/gems/yahoo-weather-1.2.0/lib/yahoo-weather/atmosphere.rb:35: syntax error, unexpected ':', expecting keyword_then or ',' or ';' or '\n'
    when 0: @barometer = Barometer::STEADY
           ^
/home/mesa/.rvm/gems/ruby-2.0.0-p247/gems/yahoo-weather-1.2.0/lib/yahoo-weather/atmosphere.rb:36: syntax error, unexpected keyword_when, expecting keyword_end
    when 1: @barometer = Barometer::RISING
        ^
/home/mesa/.rvm/gems/ruby-2.0.0-p247/gems/yahoo-weather-1.2.0/lib/yahoo-weather/atmosphere.rb:37: syntax error, unexpected keyword_when, expecting keyword_end
    when 2: @barometer = Barometer::FALLING
        ^
/home/mesa/.rvm/gems/ruby-2.0.0-p247/gems/yahoo-weather-1.2.0/lib/yahoo-weather/atmosphere.rb:40: syntax error, unexpected keyword_end, expecting end-of-input
    from /home/mesa/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
    from /home/mesa/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
    from /home/mesa/.rvm/gems/ruby-2.0.0-p247/gems/yahoo-weather-1.2.0/lib/yahoo-weather.rb:32:in `<top (required)>'
    from /home/mesa/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:133:in `require'
    from /home/mesa/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
    from /home/mesa/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:142:in `require'
    from (irb):2
    from /home/mesa/.rvm/rubies/ruby-2.0.0-p247/bin/irb:16:in `<main>'

```

**Comment by thepoppingone** [comment]
Hi @michaelachrisco , is this issue resolved?
